#pragma once

enum PRIMITIVE_MODEL_TYPE : UINT
{
    PRIMITIVE_MODEL_TYPE_SQUARE = 0,
    PRIMITIVE_MODEL_TYPE_BOX,
};

enum MESH_TYPE : UINT
{
    MESH_TYPE_UNKNOWN = 0,
    MESH_TYPE_DEFAULT,
    MESH_TYPE_SKINNED,
};
