#pragma once

enum MESH_TYPE : UINT
{
    MESH_TYPE_DEFAULT = 0,
    MESH_TYPE_SKINNED,
    MESH_TYPE_UNKNOWN,
};

enum PRIMITIVE_MODEL_TYPE : UINT
{
    PRIMITIVE_MODEL_TYPE_SQUARE = 0,
    PRIMITIVE_MODEL_TYPE_BOX,
};
